# main.yml - Promote Administrator accounts for the new server.
---
- name: promote floor manager
  win_user:
    name: fflinch
    groups: Administrators
    groups_action: add

- name: promote management user
  win_user:
    name: mgmtadmin
    groups: Administrators
    groups_action: add

- name: rename host
  win_shell: Rename-Computer floor{{ floornumber }}-server

- name: reboot host
  win_reboot:
